In [2]:
import pandas as pd
import numpy as np

In [3]:
price = np.array([2,3,2,4,5])
vol = price * 20000

In [5]:
df = pd.DataFrame({'Price':price,'Vol':vol})

In [21]:
df.at[1,'Price']

3

In [35]:
def rc1(data):
    if data['Price'] > 3:
        return data['Price']
    else:
        return data['Price'] * data['Vol']

In [59]:
df.apply(rc2,axis=1)

AttributeError: ("'Series' object has no attribute 'iterrows'", 'occurred at index 0')

In [57]:
def rc2(df):
    for index, row in df.iterrows():
        if index > 0:
           s = df.at[index-1,'Vol']
           return s
        else :
           s = df.at[index,'Vol']
           return s

In [60]:
rc2(df)

40000

In [40]:
type(df)

pandas.core.frame.DataFrame

In [50]:
df

Price     Vol
0      2   40000
1      3   60000
2      2   40000
3      4   80000
4      5  100000

In [53]:
for index, row in df.iterrows():
    if index > 0:
       print (df.at[index-1,'Vol'])

40000
60000
40000
80000


In [64]:
def rc2(df):
    for index, row in df.iterrows():
        if index > 0:
           s = df.at[index-1,'Vol']
           df['Final'] = s
           return df
       

In [65]:
rc2(df)

Price     Vol  Final
0      2   40000  40000
1      3   60000  40000
2      2   40000  40000
3      4   80000  40000
4      5  100000  40000

In [ ]:
def RSI(series, period):
 delta = series.diff().dropna()
 u = delta * 0
 d = u.copy()
 u[delta > 0] = delta[delta > 0]
 d[delta < 0] = -delta[delta < 0]
 u[u.index[period-1]] = np.mean( u[:period] ) #first value is sum of avg gains
 u = u.drop(u.index[:(period-1)])
 d[d.index[period-1]] = np.mean( d[:period] ) #first value is sum of avg losses
 d = d.drop(d.index[:(period-1)])
 rs = pd.stats.moments.ewma(u, com=period-1, adjust=False) / \
 pd.stats.moments.ewma(d, com=period-1, adjust=False)
 return 100 - 100 / (1 + rs)

In [69]:
delta = df['Vol'].diff().dropna()

Date  Price     Vol
0 2019-10-01      5  100000
1 2019-10-02      5  100000
2 2019-10-03      6  120000
3 2019-10-04      7  140000
4 2019-10-05      8  160000
5 2019-10-06      9  180000
6 2019-10-07     10  200000

In [86]:
series = df['Price']
period = df['Date']

In [88]:
delta = series.diff().dropna()
u = delta * 0
d = u.copy()
u[delta > 0] = delta[delta > 0]
d[delta < 0] = -delta[delta < 0]
u[u.index[period-1]] = np.mean( u[:period] )

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.numeric.Int64Index'> with these indexers [0   2019-10-01
1   2019-10-02
2   2019-10-03
3   2019-10-04
4   2019-10-05
5   2019-10-06
6   2019-10-07
Name: Date, dtype: datetime64[ns]] of <class 'pandas.core.series.Series'>

In [120]:
date = pd.date_range('2019-10-01','2019-10-07')
price = np.array([5,5,6,7,8,9,10])
vol = np.array([10000,5000,10000,15000,10000,90000,1000])

df = pd.DataFrame({'Date':date,'Price':price,'Vol':vol})

df

Date  Price    Vol
0 2019-10-01      5  10000
1 2019-10-02      5   5000
2 2019-10-03      6  10000
3 2019-10-04      7  15000
4 2019-10-05      8  10000
5 2019-10-06      9  90000
6 2019-10-07     10   1000

In [121]:
df['Chg'] = df['Price'].pct_change()
df['Diff'] = df['Vol'].diff()

In [134]:
df

Date  Price    Vol       Chg     Diff     Gain     Lost
0 2019-10-01      5  10000       NaN      NaN      NaN      NaN
1 2019-10-02      5   5000  0.000000  -5000.0      NaN  -5000.0
2 2019-10-03      6  10000  0.200000   5000.0   5000.0   5000.0
3 2019-10-04      7  15000  0.166667   5000.0   5000.0   5000.0
4 2019-10-05      8  10000  0.142857  -5000.0      NaN  -5000.0
5 2019-10-06      9  90000  0.125000  80000.0  80000.0  80000.0
6 2019-10-07     10   1000  0.111111 -89000.0      NaN -89000.0

In [133]:
df.loc[df['Diff']>0,'Gain'] = df['Diff']
df.loc[df['Diff']<0,'Lost'] = df['Diff']

In [130]:
true avg = df['Gain'].sum()/df.shape[0]

12857.142857142857

In [135]:
prices = np.array([5,6,5,6,7,8,9,10])

In [141]:
deltas = np.diff(prices)

In [146]:
deltas, deltas[:3]

(array([ 1, -1,  1,  1,  1,  1,  1]), array([ 1, -1,  1]))

In [147]:
deltas[deltas>=0]

array([1, 1, 1, 1, 1, 1])

In [148]:
np.zeros_like(prices)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [139]:
def rsiFunc(prices, n=14):
    deltas = np.diff(prices)
    seed = deltas[:n+1]


In [151]:
def rsiFunc(prices, n=14):
    deltas = np.diff(prices)
    seed = deltas[:n+1]
    up = seed[seed>=0].sum()/n
    down = -seed[seed<0].sum()/n
    rs = up/down
    rsi = np.zeros_like(prices)
    rsi[:n] = 100. - 100./(1.+rs)
    
    for i in range(n, len(prices)):
        delta = deltas[i-1] # cause the diff is 1 shorter

    if delta>0:
        upval = delta
        downval = 0.
    else:
        upval = 0.
        downval = -delta
    
    up = (up*(n-1) + upval)/n
    down = (down*(n-1) + downval)/n
    
    rs = up/down
    rsi[i] = 100. - 100./(1.+rs)
    
    return rsi

In [153]:
prices = np.random.rand(20)

In [154]:
rsiFunc(prices)

array([40.83839399, 40.83839399, 40.83839399, 40.83839399, 40.83839399,
       40.83839399, 40.83839399, 40.83839399, 40.83839399, 40.83839399,
       40.83839399, 40.83839399, 40.83839399, 40.83839399,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        , 45.23505284])