In [2]:
import pandas as pd
import numpy as np

In [3]:
revenue   = pd.Series([14,19,18], index=(1,2,3))
netincome = pd.Series([5,6,6], index = (1,2,3))

In [34]:
np.random.seed(1)
a = np.random.randn(10,4)

In [41]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)    # it will be (2,3) >>> 2 rows and 3 columns

# if you want to reshape it to 3 cols 2 rows
a.shape = (3,2)

a

(2, 3)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [1]:
# an array of evenly spaced numbers 
import numpy as np 
a = np.arange(24) 
a



# this is one dimensional array 
import numpy as np 
a = np.arange(24) 
a.ndim  

# now reshape it 
b = a.reshape(2,4,3)    # split into 2 main groups, then each group contains 4 rows and 3 columns
b 
# b is having three dimensions


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [27]:
a[:,:1]   # slicer column 1 

array([[ 1.62434536],
       [ 0.86540763],
       [ 0.3190391 ],
       [-0.3224172 ],
       [-0.17242821],
       [-1.10061918],
       [ 0.90085595],
       [-0.26788808],
       [-0.6871727 ],
       [-1.11731035]])

In [22]:
a[:,1:2]  # slice column 2 

array([[-0.90145854],
       [-1.9792738 ],
       [ 2.808147  ],
       [-0.42209023],
       [-1.08409492],
       [ 1.34285141],
       [-0.95672561],
       [-0.36806071],
       [ 0.35379373],
       [ 0.13030729]])

In [20]:
# slicer the first row
a[0]

array([-0.45889573, -0.90145854, -1.10798877,  1.12352766])

In [86]:
df = pd.DataFrame(np.random.randn(10, 4))


In [88]:
pieces = [df[:3], df[3:7], df[7:]]


In [2]:
import numpy as np
revenue = np.array([1,2,3,4,5])
netincome = np.array([10,20,30,40,50])

In [5]:
me = np.vstack((revenue,netincome))

In [9]:
df.index=['a','b','c','d','e']

In [8]:
import pandas as pd
df = pd.DataFrame({'Month1':me[0],'Month2':me[1]})
df

Month1  Month2
0       1      10
1       2      20
2       3      30
3       4      40
4       5      50

In [10]:
df

Month1  Month2
a       1      10
b       2      20
c       3      30
d       4      40
e       5      50

In [11]:
import pandas as pd

data = {'name': ['Somu', 'Kiku', 'Amol', 'Lini'],
	'physics': [68, 74, 77, 78],
	'chemistry': [84, 56, 73, 69],
	'algebra': [78, 88, 82, 87]}


In [12]:
df_marks = pd.DataFrame(data)
df_marks

name  physics  chemistry  algebra
0  Somu       68         84       78
1  Kiku       74         56       88
2  Amol       77         73       82
3  Lini       78         69       87

In [13]:
new_row = {'name':'Geo', 'physics':87, 'chemistry':92, 'algebra':97}
#append row to the dataframe
df_marks = df_marks.append(new_row, ignore_index=True)


In [14]:
df_marks

name  physics  chemistry  algebra
0  Somu       68         84       78
1  Kiku       74         56       88
2  Amol       77         73       82
3  Lini       78         69       87
4   Geo       87         92       97

In [24]:
df = pd.DataFrame({'val':np.repeat(250,7)})
df.index = pd.date_range('2019-10-01','2019-12-31', freq='14D')

df

val
2019-10-01  250
2019-10-15  250
2019-10-29  250
2019-11-12  250
2019-11-26  250
2019-12-10  250
2019-12-24  250

In [30]:
df['val'].str.contain

2019-10-01    250
2019-10-15    250
2019-10-29    250
2019-11-12    250
2019-11-26    250
2019-12-10    250
2019-12-24    250
Freq: 14D, Name: val, dtype: int32

In [64]:
animals

kind  height  weight
0  cat     9.1     7.9
1  dog     6.0     7.5
2  cat     9.5     9.9
3  dog    34.0   198.0

In [65]:
animals.groupby('kind').sum()

height  weight
kind                
cat     18.6    17.8
dog     40.0   205.5

In [24]:
url = 'https://www.ozlotteries.com/wednesday-lotto/statistics'

In [25]:
dfs = pd.read_html(url)

dfs

ValueError: No tables found

In [16]:
import numpy as np

In [17]:
df = pd.DataFrame(randn(2, 2))
s = df.to_html(float_format='{0:.40g}'.format)
dfin = pd.read_html(s, index_col=0)

NameError: name 'randn' is not defined

In [18]:
dfs

[                                             Bank Name                City  \
 0                                 The Enloe State Bank              Cooper   
 1                  Washington Federal Bank for Savings             Chicago   
 2      The Farmers and Merchants State Bank of Argonia             Argonia   
 3                                  Fayette County Bank          Saint Elmo   
 4    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
 5                                       First NBC Bank         New Orleans   
 6                                        Proficio Bank  Cottonwood Heights   
 7                        Seaway Bank and Trust Company             Chicago   
 8                               Harvest Community Bank          Pennsville   
 9                                          Allied Bank            Mulberry   
 10                        The Woodbury Banking Company            Woodbury   
 11                              First CornerStone B

In [20]:
t = dfs[0]
type(t)

pandas.core.frame.DataFrame

In [21]:
t[0:2]

Bank Name     City  ST   CERT  \
0                 The Enloe State Bank   Cooper  TX  10716   
1  Washington Federal Bank for Savings  Chicago  IL  30570   

  Acquiring Institution       Closing Date      Updated Date  
0    Legend Bank, N. A.       May 31, 2019     June 18, 2019  
1    Royal Savings Bank  December 15, 2017  February 1, 2019

In [23]:
t[t.City='Chicago']

SyntaxError: invalid syntax (<ipython-input-23-3ce69c93d8a1>, line 1)

In [36]:
from tabula import read_pdf

In [39]:
df = read_pdf("H:/SharedLaptop/CBA.pdf")

In [47]:
a = df[31:32]

In [52]:
a.iloc[:,1:5]

2011  2012       2013  2014
31  NaN   NaN  2.53 2.25  2.11

In [50]:
a

2009 2010 2011  2012       2013  2014  \
31  201 Sussex Street, Sydney, NSW 2000  NaN   NaN  2.53 2.25  2.11   

         2015  2016       2017  2018        YTD Performance  
31  2.33 2.78  2.84  2.78 2.35  2.23  1.90 2.13  Price/Book

In [63]:
df = pd.DataFrame(np.random.randn(8, 4), columns=['2016', '2017', '2018', '2019'])

In [64]:
df

2016      2017      2018      2019
0 -0.517015 -0.398152 -0.275460 -1.371037
1  0.213782  1.055123  0.227594  0.016428
2 -1.563594 -0.438396  0.125495  0.603876
3  0.052311 -0.904486 -0.823760 -0.062085
4  0.962081 -2.026449  2.294269  0.754720
5 -0.192392 -0.620497 -1.378860  0.665932
6 -0.683663 -1.622223 -0.447584 -1.178019
7  1.315376 -0.796453 -1.780724 -0.827947

In [72]:
val = df.iloc[3]

In [79]:
df.append(val2, ignore_index=True)

2016      2017      2018      2019
0 -0.517015 -0.398152 -0.275460 -1.371037
1  0.213782  1.055123  0.227594  0.016428
2 -1.563594 -0.438396  0.125495  0.603876
3  0.052311 -0.904486 -0.823760 -0.062085
4  0.962081 -2.026449  2.294269  0.754720
5 -0.192392 -0.620497 -1.378860  0.665932
6 -0.683663 -1.622223 -0.447584 -1.178019
7  1.315376 -0.796453 -1.780724 -0.827947
8  1.000000  2.000000  3.000000  4.000000

In [74]:
type(val)

pandas.core.series.Series

In [81]:
df

2016      2017      2018      2019
0 -0.517015 -0.398152 -0.275460 -1.371037
1  0.213782  1.055123  0.227594  0.016428
2 -1.563594 -0.438396  0.125495  0.603876
3  0.052311 -0.904486 -0.823760 -0.062085
4  0.962081 -2.026449  2.294269  0.754720
5 -0.192392 -0.620497 -1.378860  0.665932
6 -0.683663 -1.622223 -0.447584 -1.178019
7  1.315376 -0.796453 -1.780724 -0.827947

In [78]:
val2 = pd.Series([1,2,3,4],index=['2016','2017','2018','2019'])
val2

2016    1
2017    2
2018    3
2019    4
dtype: int64

In [96]:
mydf = pd.DataFrame({'a':a,'b':b})
mydf

a  b
0  1  3
1  2  4

In [97]:
a = [1,2]
b = [3,4]

In [102]:
myval = mydf.iloc[1:2]

In [66]:
type(myval)

NameError: name 'myval' is not defined

In [104]:
myval


a  b
1  2  4

In [106]:
mydf.columns

Index(['a', 'b'], dtype='object')

In [107]:
mydf.index

RangeIndex(start=0, stop=2, step=1)