In [1]:
import sklearn.datasets
iris_dataset = sklearn.datasets.load_iris()

In [2]:
iris_dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
iris_dataset.keys()   # load the keys

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [4]:
X, y = iris_dataset['data'], iris_dataset['target']

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
X.shape

(150, 4)

In [8]:
y.shape

(150,)

In [10]:
type(iris_dataset)

sklearn.utils.Bunch

In [11]:
type(X)

numpy.ndarray

In [13]:
import numpy as np
np.unique(y)  # find unique values in a column

array([0, 1, 2])

In [104]:

# there are a few datasets in sklearn

import sklearn.datasets
iris = sklearn.datasets.load_iris()
boston = sklearn.datasets.load_boston()
cancer = sklearn.datasets.load_breast_cancer()
diabetes = sklearn.datasets.load_diabetes()
digits = sklearn.datasets.load_digits()

In [106]:
digits.keys()

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

In [119]:
x = digits['data']

In [120]:
y = digits['target']

In [129]:
x[1796]

array([ 0.,  0., 10., 14.,  8.,  1.,  0.,  0.,  0.,  2., 16., 14.,  6.,
        1.,  0.,  0.,  0.,  0., 15., 15.,  8., 15.,  0.,  0.,  0.,  0.,
        5., 16., 16., 10.,  0.,  0.,  0.,  0., 12., 15., 15., 12.,  0.,
        0.,  0.,  4., 16.,  6.,  4., 16.,  6.,  0.,  0.,  8., 16., 10.,
        8., 16.,  8.,  0.,  0.,  1.,  8., 12., 14., 12.,  1.,  0.])

In [18]:
X = boston['data']

In [19]:
X.shape

(506, 13)

In [47]:
import numpy as np
np.random.seed(10)


x0, x1 = np.random.randn(10,2), np.random.rand(10,2) + (1,1) 

In [50]:
x = np.vstack((x0,x1))  # this basically just combines x0, x1 so you end up with 20 rows

x0.shape
x1.shape
x.shape

(20, 2)

In [63]:
y = [0] * 10 + [1] * 10  # what it does basically creates 0 * 10 times and 1 * 10 times
y


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [64]:
x

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021],
       [ 0.43302619,  1.20303737],
       [-0.96506567,  1.02827408],
       [ 0.22863013,  0.44513761],
       [-1.13660221,  0.13513688],
       [ 1.484537  , -1.07980489],
       [ 1.44183317,  1.43401399],
       [ 1.61776698,  1.51313824],
       [ 1.65039718,  1.60103895],
       [ 1.8052232 ,  1.52164715],
       [ 1.90864888,  1.31923609],
       [ 1.09045935,  1.30070006],
       [ 1.11398436,  1.82868133],
       [ 1.04689632,  1.62628715],
       [ 1.54758616,  1.819287  ],
       [ 1.19894754,  1.8568503 ]])

In [66]:
x.shape

(10, 2)

In [67]:
from sklearn import svm
svm.SVC(kernel='linear').fit(x,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [70]:
svm.SVC(kernel='linear').fit(x,y).predict([[1,1.8]])  # predict position 1 1.8 and result is 1

array([1])

In [69]:
y

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [71]:
from sklearn.ensemble import RandomForestClassifier

In [75]:
train = [[1,2,3],[2,5,1],[2,1,7]]
target = [0,1,0]

In [76]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(train,target)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [84]:
test = [[2,5,1]]   # the answer should be one as per above train
rf.predict(test)

array([1])

In [86]:
from sklearn.metrics import classification_report
y_true = [0,1,2,2,2]
y_pred = [0,0,2,2,1]
target_names = ['class 0','class 1','class 2']
print(classification_report(y_true,y_pred,target_names = target_names))

              precision    recall  f1-score   support

     class 0       0.50      1.00      0.67         1
     class 1       0.00      0.00      0.00         1
     class 2       1.00      0.67      0.80         3

    accuracy                           0.60         5
   macro avg       0.50      0.56      0.49         5
weighted avg       0.70      0.60      0.61         5



AttributeError: 'list' object has no attribute 'unique'

In [89]:
# gradien boosting
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.datasets import load_iris
iris_dataset = load_iris()
X,y = iris_dataset.data, iris_dataset.target

In [90]:
# split the data into training and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [94]:
gbc = GradientBoostingClassifier()
gbc.fit(X_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [96]:
gbc.score(X_test,y_test)

1.0

In [97]:
gbc.n_estimators

100

In [100]:
from sklearn.tree import DecisionTreeClassifier

train = [[1,2,3],[2,5,1],[2,1,7]]
target = [10,20,30]


dectree = DecisionTreeClassifier(random_state=0)
dectree.fit(train,target)

test = [[2,2,3]]
dectree.predict(test)

array([10])

In [101]:
# visualise the output

import pydot
import StringIO


dotfile = StringIO.StringIO()
tree.export_graphviz(dectree, out_file=dotfile)
(graph,)=pydot.graph_from_dot_data(dotfile.getvalue())
graph.write_png("dtree.png")
graph.write_pdf("dtree.pdf")

ModuleNotFoundError: No module named 'pydot'

In [103]:
# installing packages from jupyter.... use below command
pip install pydot

Note: you may need to restart the kernel to use updated packages.


  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000047805F8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',)': /simple/pydot/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004780518>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',)': /simple/pydot/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000047804E0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',)': /simple/pydot/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)